/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fdr.gomes.app;

import com.fdr.gomes.bean.Pedido;
import com.fdr.gomes.rn.PedidoRN;
import com.fdr.gomes.swing.FazerPedido;
import com.fdr.gomes.swing.ListarPedidos;
import com.fdr.gomes.swing.ManutencaoGarcom;
import com.fdr.gomes.swing.ManutencaoMesa;
import com.fdr.gomes.swing.ManutencaoProduto;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author 631410128
 */
public class RestauranteSwing extends javax.swing.JFrame {

    /**
     * Creates new form RestauranteSwing
     */
    public RestauranteSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        menuAtendimento = new javax.swing.JMenu();
        menuItemPedido = new javax.swing.JMenuItem();
        menuItemListarPedidos = new javax.swing.JMenuItem();
        menuItemRelatorio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();
        menuMesa = new javax.swing.JMenu();
        menuItemMesaManutencao = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuItemProdutoManutencao = new javax.swing.JMenuItem();
        menuGarcom = new javax.swing.JMenu();
        menuItemGarcomManutencao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante TRI bom");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        menuAtendimento.setText("Atendimento");

        menuItemPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemPedido.setText("Fazer Pedido");
        menuItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPedidoActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemPedido);

        menuItemListarPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuItemListarPedidos.setText("Listar Pedidos");
        menuItemListarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarPedidosActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemListarPedidos);

        menuItemRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuItemRelatorio.setText("Relatório");
        menuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemRelatorio);
        menuAtendimento.add(jSeparator1);

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemSair);

        menubar.add(menuAtendimento);

        menuMesa.setText("Mesa");

        menuItemMesaManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuItemMesaManutencao.setText("Manutenção");
        menuItemMesaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMesaManutencaoActionPerformed(evt);
            }
        });
        menuMesa.add(menuItemMesaManutencao);

        menubar.add(menuMesa);

        menuProduto.setText("Produto");

        menuItemProdutoManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuItemProdutoManutencao.setText("Manutenção");
        menuItemProdutoManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutoManutencaoActionPerformed(evt);
            }
        });
        menuProduto.add(menuItemProdutoManutencao);

        menubar.add(menuProduto);

        menuGarcom.setText("Garçom");

        menuItemGarcomManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuItemGarcomManutencao.setText("Manutenção");
        menuItemGarcomManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGarcomManutencaoActionPerformed(evt);
            }
        });
        menuGarcom.add(menuItemGarcomManutencao);

        menubar.add(menuGarcom);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPedidoActionPerformed
        // TODO add your handling code here:
        FazerPedido fp = new FazerPedido();
        desktopPane.add(fp);
        fp.setVisible(true);
    }//GEN-LAST:event_menuItemPedidoActionPerformed

    private void menuItemListarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarPedidosActionPerformed
        // TODO add your handling code here:
        ListarPedidos lp = new ListarPedidos();
        desktopPane.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_menuItemListarPedidosActionPerformed

    private void menuItemMesaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMesaManutencaoActionPerformed
        // TODO add your handling code here:
        ManutencaoMesa mm = new ManutencaoMesa();
        desktopPane.add(mm);
        mm.setVisible(true);
    }//GEN-LAST:event_menuItemMesaManutencaoActionPerformed

    private void menuItemProdutoManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutoManutencaoActionPerformed
        // TODO add your handling code here:
        ManutencaoProduto mp = new ManutencaoProduto();
        desktopPane.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_menuItemProdutoManutencaoActionPerformed

    private void menuItemGarcomManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGarcomManutencaoActionPerformed
        // TODO add your handling code here:
        ManutencaoGarcom mg = new ManutencaoGarcom();
        desktopPane.add(mg);
        mg.setVisible(true);
                
    }//GEN-LAST:event_menuItemGarcomManutencaoActionPerformed

    private void menuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioActionPerformed
        // TODO add your handling code here:
        try {
            PedidoRN rn = new PedidoRN();
            List<Pedido> listaPedido = rn.pesquisar("");
            StringBuilder saidaCSV = new StringBuilder();
            
            saidaCSV.append("CODIGO;DATA;MESA;GARCOM;VALOR").append("\r\n");
            
            for (Pedido p : listaPedido) {
                saidaCSV.append(p.getCodigo()).append(";");
                saidaCSV.append(new SimpleDateFormat("dd/MM/yyyy HH:mm").format(p.getData())).append(";");
                saidaCSV.append(p.getMesa().getNumero()).append(";");
                saidaCSV.append(p.getGarcom().getNome()).append(";");
                saidaCSV.append(p.getTotalPedido()).append(";");
                saidaCSV.append("\r\n");
            }
            
            FileUtils.writeStringToFile(new File("relatorio.csv"), saidaCSV.toString());
            JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_menuItemRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestauranteSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAtendimento;
    private javax.swing.JMenu menuGarcom;
    private javax.swing.JMenuItem menuItemGarcomManutencao;
    private javax.swing.JMenuItem menuItemListarPedidos;
    private javax.swing.JMenuItem menuItemMesaManutencao;
    private javax.swing.JMenuItem menuItemPedido;
    private javax.swing.JMenuItem menuItemProdutoManutencao;
    private javax.swing.JMenuItem menuItemRelatorio;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuMesa;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
